# Enable all linters except the deprecated and annoying ones
linters:
  enable-all: true
  disable:
    # Deprecated
    - nosnakecase
    - exhaustivestruct
    - varcheck
    - interfacer
    - structcheck
    - maligned
    - scopelint
    - ifshort
    - golint
    - deadcode
    # Annoying, enable in prod
    - godox # TODO: Turn on when I want to tackle TODOs
    # Not relevant for me
    - depguard
    # Causes false positives
    - gocritic # Does not recognize errors.Is
