[connection]
user = "<USER_DN>"
password = "<AD_PASSWORD>"

[template.example_de]
# lang_code = "de" # https://www.andiamo.co.uk/resources/iso-language-codes/
# files = ["example_de.html", "example_de.rtf", "example_de.txt"]
ad_filter = "(&(objectclass=person)(mail=*))" # TODO: Make this the default filter
base_dn = "OU=Benutzer,DC=example,DC=local"
exclude_emails = ["scanner@example.local"]    # Case insensitive

[template.example_de.field_mapping]
first_name = "sn"
last_name = "givenName"
title = "title"
department = "department"
company = "company"
street = "streetAddress"
postalCode = "postalCode"
city = "l"
country = "co"
phone = "telephoneNumber"
fax = "facsimileTelephoneNumber"
web = "wWWHomePage"

[template.example_en]
# lang_code = "en-gb" # https://www.andiamo.co.uk/resources/iso-language-codes/
# files = ["example_en.html", "example_en.rtf", "example_en.txt"]
ad_filter = "(&(objectclass=person)(mail=*))"
base_dn = "OU=Benutzer,DC=example,DC=local"
exclude_emails = ["scanner@example.local"]    # Case insensitive

[template.example_en.field_mapping]
first_name = "sn"
last_name = "givenName"
title = "title"
department = "department"
company = "company"
street = "streetAddress"
postalCode = "postalCode"
city = "l"
country = "co"
phone = "telephoneNumber"
fax = "facsimileTelephoneNumber"
web = "wWWHomePage"
